-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asimsMeta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asimsMeta` ;

-- -----------------------------------------------------
-- Schema asimsMeta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asimsMeta` DEFAULT CHARACTER SET latin1 ;
USE `asimsMeta` ;

-- -----------------------------------------------------
-- Table `asimsMeta`.`Attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`Attempt` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`Attempt` (
  `user` INT(11) NULL DEFAULT NULL,
  `successful` TINYINT(1) NULL DEFAULT NULL,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `port` VARCHAR(255) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`Auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`Auth` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`Auth` (
  `user` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `resetToken` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`Jwt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`Jwt` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`Jwt` (
  `token` LONGTEXT NULL DEFAULT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  `revoked` TINYINT(1) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`ResetToken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`ResetToken` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`ResetToken` (
  `token` LONGTEXT NULL DEFAULT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`Role` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`Role` (
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`ToDoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`ToDoList` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`ToDoList` (
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `state` TINYINT(1) NULL DEFAULT NULL,
  `userid` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`Use`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`Use` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`Use` (
  `remoteAddress` VARCHAR(255) NULL DEFAULT NULL,
  `jsonWebToken` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `asimsMeta`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asimsMeta`.`User` ;

CREATE TABLE IF NOT EXISTS `asimsMeta`.`User` (
  `auth` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `role` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERT into ROLE Table
INSERT INTO role(role,id) VALUES ('reader',1),('writer',2),('admin',3);
