-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asimsMeta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `asimsMeta` ;

-- -----------------------------------------------------
-- Schema asimsMeta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asimsMeta` DEFAULT CHARACTER SET latin1 ;
USE `asimsMeta` ;

-- -----------------------------------------------------
-- Table `Attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Attempt` ;

CREATE TABLE IF NOT EXISTS `Attempt` (
  `user` INT(11) NULL DEFAULT NULL,
  `successful` TINYINT(1) NULL DEFAULT NULL,
  `ip` VARCHAR(255) NULL DEFAULT NULL,
  `port` VARCHAR(255) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auth` ;

CREATE TABLE IF NOT EXISTS `Auth` (
  `user` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `resetToken` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Jwt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Jwt` ;

CREATE TABLE IF NOT EXISTS `Jwt` (
  `token` LONGTEXT NULL DEFAULT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  `revoked` TINYINT(1) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ResetToken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ResetToken` ;

CREATE TABLE IF NOT EXISTS `ResetToken` (
  `token` LONGTEXT NULL DEFAULT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Role` ;

CREATE TABLE IF NOT EXISTS `Role` (
  `role` VARCHAR(255) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ToDoList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ToDoList` ;

CREATE TABLE IF NOT EXISTS `ToDoList` (
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `state` TINYINT(1) NULL DEFAULT NULL,
  `userid` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Use`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Use` ;

CREATE TABLE IF NOT EXISTS `Use` (
  `remoteAddress` VARCHAR(255) NULL DEFAULT NULL,
  `jsonWebToken` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `auth` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `role` INT(11) NULL DEFAULT NULL,
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERT into ROLE Table
INSERT INTO Role(role,id) VALUES ('reader',1),('writer',2),('admin',3);
-- INSERT credentials for users
INSERT INTO `User` (`auth`,`username`,`firstName`,`lastName`,`email`,`role`,`id`) VALUES 
  (1,'support','support','account','support@asims.ca',3,1);
INSERT INTO `Auth` VALUES
  (1,'support','$2a$10$voVXI41FVwkXEj48KeZwu.x/5inCTFELD5mxrOeTO4FGerJWg5z3K',NULL,1);
